[2024-04-02T16:57:34.872+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T00:15:00+00:00 [queued]>
[2024-04-02T16:57:34.926+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T00:15:00+00:00 [queued]>
[2024-04-02T16:57:34.928+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-02T16:57:35.119+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data_api> on 2024-04-02 00:15:00+00:00
[2024-04-02T16:57:35.198+0000] {standard_task_runner.py:60} INFO - Started process 235955 to run task
[2024-04-02T16:57:35.195+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_get_air4thai', 'get_data_api', 'scheduled__2024-04-02T00:15:00+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/test_get_air4thai.py', '--cfg-path', '/tmp/tmpb2f_qzi7']
[2024-04-02T16:57:35.228+0000] {standard_task_runner.py:88} INFO - Job 239: Subtask get_data_api
[2024-04-02T16:57:35.733+0000] {task_command.py:423} INFO - Running <TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T00:15:00+00:00 [running]> on host c5a6ac367c49
[2024-04-02T16:57:36.455+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_get_air4thai' AIRFLOW_CTX_TASK_ID='get_data_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T00:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T00:15:00+00:00'
[2024-04-02T16:57:36.563+0000] {test_get_air4thai.py:27} INFO - **** filename : data_air_2024_04_02_1600.json
[2024-04-02T16:57:36.566+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_get_air4thai.py", line 31, in _get_data_api
    json.dump(data, file)
NameError: name 'data' is not defined
[2024-04-02T16:57:36.660+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=test_get_air4thai, task_id=get_data_api, execution_date=20240402T001500, start_date=20240402T165734, end_date=20240402T165736
[2024-04-02T16:57:37.359+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 239 for task get_data_api (name 'data' is not defined; 235955)
[2024-04-02T16:57:37.462+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T16:57:37.849+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T17:23:10.172+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T00:15:00+00:00 [queued]>
[2024-04-02T17:23:10.259+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T00:15:00+00:00 [queued]>
[2024-04-02T17:23:10.270+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-02T17:23:10.415+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data_api> on 2024-04-02 00:15:00+00:00
[2024-04-02T17:23:10.433+0000] {standard_task_runner.py:60} INFO - Started process 237318 to run task
[2024-04-02T17:23:10.505+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_get_air4thai', 'get_data_api', 'scheduled__2024-04-02T00:15:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/test_get_air4thai.py', '--cfg-path', '/tmp/tmp52k08kzo']
[2024-04-02T17:23:10.550+0000] {standard_task_runner.py:88} INFO - Job 266: Subtask get_data_api
[2024-04-02T17:23:11.118+0000] {task_command.py:423} INFO - Running <TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T00:15:00+00:00 [running]> on host c5a6ac367c49
[2024-04-02T17:23:12.222+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_get_air4thai' AIRFLOW_CTX_TASK_ID='get_data_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T00:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T00:15:00+00:00'
[2024-04-02T17:23:12.920+0000] {test_get_air4thai.py:31} INFO - **** filename : data_air_2024_04_03_0000.json
[2024-04-02T17:23:13.214+0000] {test_get_air4thai.py:37} INFO - JSON data saved to /opt/***/dags/data_air4thai.json
[2024-04-02T17:23:13.225+0000] {test_get_air4thai.py:41} INFO - local file path : /opt/***/dags/data_air4thai.json
[2024-04-02T17:23:13.255+0000] {test_get_air4thai.py:45} INFO - bucket name : ds525-capstone-test-49
[2024-04-02T17:23:13.283+0000] {test_get_air4thai.py:48} INFO - dst : data_raw_air/data_air_2024_04_03_0000.json
[2024-04-02T17:23:13.385+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-02T17:23:13.411+0000] {base.py:83} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-02T17:23:17.359+0000] {gcs.py:557} INFO - File /opt/***/dags/data_air4thai.json uploaded to data_raw_air/data_air_2024_04_03_0000.json in ds525-capstone-test-49 bucket
[2024-04-02T17:23:17.364+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-02T17:23:17.483+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=test_get_air4thai, task_id=get_data_api, execution_date=20240402T001500, start_date=20240402T172310, end_date=20240402T172317
[2024-04-02T17:23:17.779+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-02T17:23:17.921+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
