[2024-03-26T16:49:18.443+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_get_tmd_api.upload_to_gcs manual__2024-03-26T16:48:57.695992+00:00 [queued]>
[2024-03-26T16:49:18.469+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_get_tmd_api.upload_to_gcs manual__2024-03-26T16:48:57.695992+00:00 [queued]>
[2024-03-26T16:49:18.470+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-26T16:49:18.508+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): upload_to_gcs> on 2024-03-26 16:48:57.695992+00:00
[2024-03-26T16:49:18.521+0000] {standard_task_runner.py:60} INFO - Started process 46315 to run task
[2024-03-26T16:49:18.531+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_get_tmd_api', 'upload_to_gcs', 'manual__2024-03-26T16:48:57.695992+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/test_get_tmd_api.py', '--cfg-path', '/tmp/tmp2i_9mgrx']
[2024-03-26T16:49:18.537+0000] {standard_task_runner.py:88} INFO - Job 87: Subtask upload_to_gcs
[2024-03-26T16:49:18.672+0000] {task_command.py:423} INFO - Running <TaskInstance: test_get_tmd_api.upload_to_gcs manual__2024-03-26T16:48:57.695992+00:00 [running]> on host c5a6ac367c49
[2024-03-26T16:49:18.906+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_get_tmd_api' AIRFLOW_CTX_TASK_ID='upload_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T16:48:57.695992+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-26T16:48:57.695992+00:00'
[2024-03-26T16:49:18.910+0000] {test_get_tmd_api.py:61} INFO - local file path : /opt/***/dags/data_get.json
[2024-03-26T16:49:18.912+0000] {test_get_tmd_api.py:65} INFO - bucket name : ds525-capstone-test-49
[2024-03-26T16:49:18.913+0000] {test_get_tmd_api.py:68} INFO - dst : data_test/
[2024-03-26T16:49:18.938+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-26T16:49:18.951+0000] {base.py:83} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-03-26T16:49:19.929+0000] {gcs.py:557} INFO - File /opt/***/dags/data_get.json uploaded to data_test/data_get.json in ds525-capstone-test-49 bucket
[2024-03-26T16:49:19.933+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_get_tmd_api.py", line 82, in _upload_to_gcs
    os.remove(local_file_path)
NameError: name 'os' is not defined
[2024-03-26T16:49:19.960+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=test_get_tmd_api, task_id=upload_to_gcs, execution_date=20240326T164857, start_date=20240326T164918, end_date=20240326T164919
[2024-03-26T16:49:20.001+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 87 for task upload_to_gcs (name 'os' is not defined; 46315)
[2024-03-26T16:49:20.026+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-26T16:49:20.082+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
