[2024-03-26T16:32:36.791+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_get_tmd_api.upload_to_gcs manual__2024-03-26T16:27:03.360202+00:00 [queued]>
[2024-03-26T16:32:36.817+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_get_tmd_api.upload_to_gcs manual__2024-03-26T16:27:03.360202+00:00 [queued]>
[2024-03-26T16:32:36.818+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-26T16:32:36.856+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): upload_to_gcs> on 2024-03-26 16:27:03.360202+00:00
[2024-03-26T16:32:36.867+0000] {standard_task_runner.py:60} INFO - Started process 45560 to run task
[2024-03-26T16:32:36.877+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_get_tmd_api', 'upload_to_gcs', 'manual__2024-03-26T16:27:03.360202+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/test_get_tmd_api.py', '--cfg-path', '/tmp/tmp_ovd8m5a']
[2024-03-26T16:32:36.883+0000] {standard_task_runner.py:88} INFO - Job 74: Subtask upload_to_gcs
[2024-03-26T16:32:37.016+0000] {task_command.py:423} INFO - Running <TaskInstance: test_get_tmd_api.upload_to_gcs manual__2024-03-26T16:27:03.360202+00:00 [running]> on host c5a6ac367c49
[2024-03-26T16:32:37.281+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_get_tmd_api' AIRFLOW_CTX_TASK_ID='upload_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T16:27:03.360202+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-26T16:27:03.360202+00:00'
[2024-03-26T16:32:37.285+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_get_tmd_api.py", line 51, in _upload_to_gcs
    logging.info(f"file name : {filename}")
NameError: name 'filename' is not defined
[2024-03-26T16:32:37.311+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=test_get_tmd_api, task_id=upload_to_gcs, execution_date=20240326T162703, start_date=20240326T163236, end_date=20240326T163237
[2024-03-26T16:32:37.356+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 74 for task upload_to_gcs (name 'filename' is not defined; 45560)
[2024-03-26T16:32:37.409+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-26T16:32:37.458+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
