[2024-04-02T16:57:52.025+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T15:15:00+00:00 [queued]>
[2024-04-02T16:57:52.110+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T15:15:00+00:00 [queued]>
[2024-04-02T16:57:52.112+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-02T16:57:52.202+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data_api> on 2024-04-02 15:15:00+00:00
[2024-04-02T16:57:52.229+0000] {standard_task_runner.py:60} INFO - Started process 235985 to run task
[2024-04-02T16:57:52.250+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_get_air4thai', 'get_data_api', 'scheduled__2024-04-02T15:15:00+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/test_get_air4thai.py', '--cfg-path', '/tmp/tmp0t8ebt6s']
[2024-04-02T16:57:52.267+0000] {standard_task_runner.py:88} INFO - Job 255: Subtask get_data_api
[2024-04-02T16:57:52.519+0000] {task_command.py:423} INFO - Running <TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T15:15:00+00:00 [running]> on host c5a6ac367c49
[2024-04-02T16:57:52.814+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_get_air4thai' AIRFLOW_CTX_TASK_ID='get_data_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T15:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T15:15:00+00:00'
[2024-04-02T16:57:52.860+0000] {test_get_air4thai.py:27} INFO - **** filename : data_air_2024_04_02_1600.json
[2024-04-02T16:57:52.864+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_get_air4thai.py", line 31, in _get_data_api
    json.dump(data, file)
NameError: name 'data' is not defined
[2024-04-02T16:57:52.896+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=test_get_air4thai, task_id=get_data_api, execution_date=20240402T151500, start_date=20240402T165752, end_date=20240402T165752
[2024-04-02T16:57:52.946+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 255 for task get_data_api (name 'data' is not defined; 235985)
[2024-04-02T16:57:52.980+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T16:57:53.027+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T17:23:31.107+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T15:15:00+00:00 [queued]>
[2024-04-02T17:23:31.154+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T15:15:00+00:00 [queued]>
[2024-04-02T17:23:31.156+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-02T17:23:31.229+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data_api> on 2024-04-02 15:15:00+00:00
[2024-04-02T17:23:31.246+0000] {standard_task_runner.py:60} INFO - Started process 237365 to run task
[2024-04-02T17:23:31.276+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_get_air4thai', 'get_data_api', 'scheduled__2024-04-02T15:15:00+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/test_get_air4thai.py', '--cfg-path', '/tmp/tmp_5n2ll_8']
[2024-04-02T17:23:31.288+0000] {standard_task_runner.py:88} INFO - Job 282: Subtask get_data_api
[2024-04-02T17:23:31.493+0000] {task_command.py:423} INFO - Running <TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T15:15:00+00:00 [running]> on host c5a6ac367c49
[2024-04-02T17:23:31.870+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_get_air4thai' AIRFLOW_CTX_TASK_ID='get_data_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T15:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T15:15:00+00:00'
[2024-04-02T17:23:32.140+0000] {test_get_air4thai.py:31} INFO - **** filename : data_air_2024_04_03_0000.json
[2024-04-02T17:23:32.205+0000] {test_get_air4thai.py:37} INFO - JSON data saved to /opt/***/dags/data_air4thai.json
[2024-04-02T17:23:32.207+0000] {test_get_air4thai.py:41} INFO - local file path : /opt/***/dags/data_air4thai.json
[2024-04-02T17:23:32.208+0000] {test_get_air4thai.py:45} INFO - bucket name : ds525-capstone-test-49
[2024-04-02T17:23:32.210+0000] {test_get_air4thai.py:48} INFO - dst : data_raw_air/data_air_2024_04_03_0000.json
[2024-04-02T17:23:32.252+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-02T17:23:32.263+0000] {base.py:83} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-02T17:23:33.321+0000] {gcs.py:557} INFO - File /opt/***/dags/data_air4thai.json uploaded to data_raw_air/data_air_2024_04_03_0000.json in ds525-capstone-test-49 bucket
[2024-04-02T17:23:33.326+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-02T17:23:33.367+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=test_get_air4thai, task_id=get_data_api, execution_date=20240402T151500, start_date=20240402T172331, end_date=20240402T172333
[2024-04-02T17:23:33.451+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-02T17:23:33.504+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
