[2024-04-02T16:57:42.198+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T08:15:00+00:00 [queued]>
[2024-04-02T16:57:42.275+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T08:15:00+00:00 [queued]>
[2024-04-02T16:57:42.276+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-02T16:57:42.493+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data_api> on 2024-04-02 08:15:00+00:00
[2024-04-02T16:57:42.558+0000] {standard_task_runner.py:60} INFO - Started process 235967 to run task
[2024-04-02T16:57:42.591+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_get_air4thai', 'get_data_api', 'scheduled__2024-04-02T08:15:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/test_get_air4thai.py', '--cfg-path', '/tmp/tmphaqcqk90']
[2024-04-02T16:57:42.615+0000] {standard_task_runner.py:88} INFO - Job 247: Subtask get_data_api
[2024-04-02T16:57:43.027+0000] {task_command.py:423} INFO - Running <TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T08:15:00+00:00 [running]> on host c5a6ac367c49
[2024-04-02T16:57:43.612+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_get_air4thai' AIRFLOW_CTX_TASK_ID='get_data_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T08:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T08:15:00+00:00'
[2024-04-02T16:57:43.676+0000] {test_get_air4thai.py:27} INFO - **** filename : data_air_2024_04_02_1600.json
[2024-04-02T16:57:43.678+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_get_air4thai.py", line 31, in _get_data_api
    json.dump(data, file)
NameError: name 'data' is not defined
[2024-04-02T16:57:43.738+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=test_get_air4thai, task_id=get_data_api, execution_date=20240402T081500, start_date=20240402T165742, end_date=20240402T165743
[2024-04-02T16:57:43.830+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 247 for task get_data_api (name 'data' is not defined; 235967)
[2024-04-02T16:57:43.875+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T16:57:43.968+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T17:23:19.362+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T08:15:00+00:00 [queued]>
[2024-04-02T17:23:19.560+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T08:15:00+00:00 [queued]>
[2024-04-02T17:23:19.583+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-02T17:23:19.815+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_data_api> on 2024-04-02 08:15:00+00:00
[2024-04-02T17:23:19.900+0000] {standard_task_runner.py:60} INFO - Started process 237353 to run task
[2024-04-02T17:23:19.929+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_get_air4thai', 'get_data_api', 'scheduled__2024-04-02T08:15:00+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/test_get_air4thai.py', '--cfg-path', '/tmp/tmprxxpmwet']
[2024-04-02T17:23:19.941+0000] {standard_task_runner.py:88} INFO - Job 274: Subtask get_data_api
[2024-04-02T17:23:20.272+0000] {task_command.py:423} INFO - Running <TaskInstance: test_get_air4thai.get_data_api scheduled__2024-04-02T08:15:00+00:00 [running]> on host c5a6ac367c49
[2024-04-02T17:23:20.900+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_get_air4thai' AIRFLOW_CTX_TASK_ID='get_data_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T08:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T08:15:00+00:00'
[2024-04-02T17:23:21.148+0000] {test_get_air4thai.py:31} INFO - **** filename : data_air_2024_04_03_0000.json
[2024-04-02T17:23:21.223+0000] {test_get_air4thai.py:37} INFO - JSON data saved to /opt/***/dags/data_air4thai.json
[2024-04-02T17:23:21.226+0000] {test_get_air4thai.py:41} INFO - local file path : /opt/***/dags/data_air4thai.json
[2024-04-02T17:23:21.227+0000] {test_get_air4thai.py:45} INFO - bucket name : ds525-capstone-test-49
[2024-04-02T17:23:21.228+0000] {test_get_air4thai.py:48} INFO - dst : data_raw_air/data_air_2024_04_03_0000.json
[2024-04-02T17:23:21.295+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-02T17:23:21.326+0000] {base.py:83} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-02T17:23:24.001+0000] {gcs.py:557} INFO - File /opt/***/dags/data_air4thai.json uploaded to data_raw_air/data_air_2024_04_03_0000.json in ds525-capstone-test-49 bucket
[2024-04-02T17:23:24.006+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-02T17:23:24.055+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=test_get_air4thai, task_id=get_data_api, execution_date=20240402T081500, start_date=20240402T172319, end_date=20240402T172324
[2024-04-02T17:23:24.150+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-02T17:23:24.254+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
